### ISSUE TITLE
【需求】支持查询媒体内容(图片/视频)，像搜索文件一样。

### ISSUE THREAD

**Issue by PaulYan233** [wildfirechat/app-server#40]
目前能直接查看私聊/群聊的媒体内容(图片/视频)，这类功能支持应用越来越多了，我也需要。

能支持下吗，像搜索文件一样，搜索出对应的媒体内容，图片、视频、音频。

**Comment by heavyrain2012** [comment]
https://github.com/wildfirechat/im-server/issues/699 issue提到im服务项目，这里先关掉
